export const STATUS_BAR_PRIMARY_COLOR = "#1D1160";
export const FACEBOOK_BUTTON_COLOR = "#0984FE";
export const SIGNUP_BUTTON_COLOR = "#1ba7bd";
export const PARTIES_TAB_COLOR = "#dedede";
// export const TIME_CONTENT_COLOR = '#64d2ff';
export const TIME_CONTENT_COLOR = "#03A7ED";
export const JOIN_BUTTON_COLOR = "#03A7ED";
export const JOIN_BUTTON_NEW_COLOR = "#1D1160";
export const LINE_COLOR = "#9DA2B3";
export const COLLYDE_GRAY_BACKGROUND_COLOR = "#424950";
export const COLLYDE_LIGHT_GRAY_COLOR = "#E4E5E6";
export const COLLYDE_PRIMARY_BLUE_COLOR = "#03A7ED";
export const COLLYDE_MESSAGE_BUBBLE_BACKGROUND_COLOR = "#F1F1F1";
export const COLLYDE_ERROR_RED = "#e33522";

export const COLLYDE_MESSAGE_BUBBLE_BACKGROUND_NEW_COLOR = "#E56020";
export const COLLYDE_MESSAGE_BUBBLE_BACKGROUND_OTHER_NEW_COLOR = "#1D1160";
