export const TEXT_CONST = {
  SIGN_UP_FB: 'Continue with Facebook',
  SIGN_UP_APPLE: 'Continue with Apple',
  SIGN_UP_MOBILE: 'Use cell phone number',
  SIGN_OUT: 'Sign Out',
  LogoutContent: 'Are you sure you want to logout?',
  CANCEL: 'Cancel',
  CONFIRM: 'Confirm',
  CONTINUE: 'Continue',
  TERMS: 'Terms and Conditions',
  PRIVACY: 'Privacy Policy',
  TermsAndConditions: 'By signing up for Collyde, you agree to our ',
  WATCH_PARTIES: 'WATCH PARTIES',
  PULL_TO_REFRESH: 'Pull to refresh',
  EXPLORE_PARTIES: 'Explore Parties',
  NO_ROOM_JOINED: 'No Room joined.',
  OOPS: 'Oops',
  NO_WATCH_PARTY_TEXT: 'There is no watch party',
  NO_GIF_TO_DISPLAY: 'There is no Gifs to display.',
  NO_TRIVIA_QUESTIONS_TO_DISPLAY: 'There is no Trivia questions to display.',
  FaceBookLogin: 1,
  AppleLogin: 2,
  INTERNET_ERROR: 'Get your Internet right - No connection',
  SENDBIRD_ERROR: 'Please restart the app - An unexpected error occurred',
  ACCOUNT_INFO: 'Account',
  APP_SETTING: 'App Settings',
  LEGAL_INFO: 'Legal',
  COMMUNITY_INFO: 'Community',
  SETTINGS: 'Settings',
  JOIN: 'Join',
  GOT_IT: 'Got It',
  MAY_BE: 'Maybe',
  MORE_INFO: 'More Info',
  CODE_SENT: 'Code Sent',
  RESEND_CODE: 'Tap to resend code',
  NEXT: 'Next',
  FAN_GUIDELINES_TITLE: 'Fan Guidelines',
  COMMUNITY_GUIDELINE_TITLE: 'Community Guidelines',
  SHORT_FLAG_TEXT: 'You can flag other fans for unsportsmanlike conduct, which can lead to their suspension.',
  USER_BANNED_INPUT_BOX: 'You have been removed from this group.',
  REMOVE_USER_CONFIRMATION_TEXT: 'Remove user from group?',
  FLAG_MESSAGE_CONFIRMATION_TEXT: 'Flag message?',
  DEFAULT_TIMEZONE_ID: '5f33d73ac2e6a63ea52610b6',
  PARTY_STARTS_IN_ONE_MIN: 'Party starting in 1 mins!',
  PARTY_STARTS_IN_FIFTEEN_MIN: 'Party starting in 15 mins!',
  COULD_NOT_LOAD_IMAGE: 'Could not load the file.',
  IS_GROUP_HOST: 'operator',
  ENTER_MOBILE_TITLE: `What's your phone number?`,
  ENTER_EMAIL_TITLE: `Enter your email`,
  VERIFY_MOBILE_TITLE: `Verify your number`,
  ENTER_MOBILE_SUB_TITLE: `We protect our community by making sure everyone is real at Collyde.`,
  VERIFY_MOBILE_SUB_TITLE: `Enter the code we've sent by text.`,
  ENTER_EMAIL_SUB_TITLE: `Collyde doesn’t spam. Enter email to be eligible for rewards.`,
  REQUIRED_ACCESSCODE: `This room requires an access code`,
  INCORRECT_PASSWORD_JOINROOM: `Not it, try again or call someone`,
  STATUS_CODE: {
    success: 200,
    unAuthorized: 401,
  },
  INSTAGRAM_ROUTE_URL: 'https://www.instagram.com/',
  TWITTER_ROUTE_URL: 'https://mobile.twitter.com/',
  ANDROID_APP_URL: 'https://play.google.com/store/apps/details?id=com.collyde.mavericks.app',
  IOS_APP_URL: 'https://apps.apple.com/us/app/collydeparty/id1526259723'
};

export const APP_MESSAGES = {
  INTERNET_IS_TURNED_OFF: 'Internet connection is turned off',
  LOCATION_PERMISSION_REQUIRED: 'Location permission required',
  DEVICE_GPS_TURNED_OFF: 'Device GPS is turned off',
  TOO_MANY_ATTEMPTS: 'Too many attempts. Please try again later.',
  YOU_APPEARS_TO_BE_OFFLINE:
    'You appears to be offline. Kindly check your internet connection.',
  REQUEST_LOCATION_DETECTION_PERMISSION: `Allow Collyde to automatically detect your current location and show nearby users.`,
  REQUEST_TO_TURN_GPS_ON: `'Allow Collyde to turn on your phone GPS for accurate location.'`,
  TO_ENABLE_GO_TO_SETTINGS:
    'To enable, go to Settings and turn on location permission.',
  OPEN_SETTINGS: 'Open Settings',
  ALLOW_PERMISSION: 'Allow Permission',
  TURN_ON_GPS: 'Turn on GPS',
};
